language: perl6

perl6:
    - '2017.09'
    - '2017.10'
    - latest

install:
    - rakudobrew build-zef
    # Explicitly install HEAD of Cro::Core and Cro::TLS
    - zef install https://github.com/croservices/cro-core/archive/master.zip
    - zef install https://github.com/croservices/cro-tls/archive/master.zip
    - zef --debug --deps-only install .
